# -*- coding: utf-8 -*-
"""Python_practice2-ict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/annmariyafrancis/888195d60b5fb0a52142f5892a871b95/week1assignment-ict.ipynb

1. Write a python program to convert temperature in Fahrenheit
"""

# Commented out IPython magic to ensure Python compatibility.

celsius_1 = float(input("Temperature value in degree Celsius: " ))  
 
Fahrenheit_1 = (celsius_1 * 1.8) + 32  
  
print('The %.2f degree Celsius is equal to: %.2f Fahrenheit'  
#       %(celsius_1, Fahrenheit_1))

"""2. WAP in python find the area of a triangle

"""

a=float(input("side 1:"))
b=float(input("side 2:"))
c=float(input("side 3:"))
s=(a+b+c)/2
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5 
print("area of triangle %.2f"%area)

"""3. Write a Python Program to accept the details of a student like name, roll number and
mark and display it.
Sample input: Enter the name: Anisha
Enter the roll number: 21
Enter the mark: 78
Sample output:
Name: Anisha
Roll No: 21
Mark: 78
"""

a="Name:Anisha"
b="RollNo:21"
c="Mark:78"
print(a)
print(b)
print(c)

"""4. Write a Python program to get the largest number from a list.
Sample input: 12, 3, 47, 10
Sample output: 47 is the largest number
"""

list1=[12,3,47,10]
print(max(list1),"is the largest number")

"""5 Write a python program to find the average of 5 numbers"""

import math
list1=[1,2,3,4,5]
avg=sum(list1)/len(list1)
avg

"""6. Python program to insert a number to any position in a list """

nums = [ 1, 2, 3, 4, 5 ]
nums.insert(4, 10)
print(nums)

"""7. Write a program to rename a key city to a location in the following dictionary.
sample_dict = { "name": "Kelly", "age":25, "salary": 8000, "city": "New york"}
"""

sample_dict = { "name": "Kelly", "age":25, "salary": 8000, "city": "New york"}
sample_dict['location'] = sample_dict.pop('city')
print(sample_dict)

"""8. Write a Python program to change Brad’s salary to 8500 in the following dictionary.
sample_dict = {
 'emp1': {'name': 'Jhon', 'salary': 7500},
 'emp2': {'name': 'Emma', 'salary': 8000},
 'emp3': {'name': 'Brad', 'salary': 500}
}
"""

sample_dict = { 'emp1': {'name': 'Jhon', 'salary': 7500}, 'emp2': {'name': 'Emma', 'salary': 8000}, 'emp3': {'name': 'Brad', 'salary': 500} }
sample_dict['emp3']['salary']=8500
sample_dict

"""9. Write a program to copy elements 44 and 55 from the following tuple into a new tuple. Given:
tuple1 = (11, 22, 33, 44, 55, 66)
"""

tuple1 = (11, 22, 33, 44, 55, 66)
tuple1[3:5]

"""10. Counts the number of occurrences of item 50 from a tuple
 tuple1 = (50, 10, 60, 70,
50,83,567,50,81)
"""

tuple1 = (50, 10, 60, 70,50,83,567,50,81)
count = tuple1.count(50)  
print("The number of occurrences of item 50:",count)