# -*- coding: utf-8 -*-
"""Python_Data_Visualizations_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ekR-VpiH_fX__AztxbRoEkncKEFfgw-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("/content/data (1).csv")
df

df.shape

df.info()

df.isna()

df1=df.fillna(method='bfill')
df1

df1.at[7,'Duration']='60'
df1

df1.at[26,'Date']='2020/12/26'
df1

df1.plot()

df1.plot(x='Calories',y='Pulse')

df1.plot(subplots=True,figsize=(8,8));

"""Bar plot"""

df1.plot(kind='bar')

"""stacked bar plot"""

df1.plot.barh(stacked=True);

"""Histogram"""

df1.plot.hist()

df1.plot.hist(stacked=True,bins=20)

"""Boxplot"""

df1.plot.box()

"""Scatterplot"""

df1.plot.scatter(x='Calories',y='Pulse',color='red');